9 directory configuration change
WFrog2511/game-center pull request #12
Opened 2024-08-25 07:41 UTC by WFrog2511

## やったこと
・frontendディレクトリとbackendディレクトリの作成
・フロントエンド関連ファイルの移動
・バックエンド用のDockerfile(まだ空)の配置

## 注意点
・issue #9 で挙げた形式とことなり、frontendディレクトリ内にsrcディレクトリを置いている
→ 作成したソースコードのみを含むディレクトリとなり、確認しやすくなると判断したため。
・.huskyディレクトリも移動させた。
→ コミット時にpacake.jsonを見つけられず エラーが出る  かつ  バックエンドも個別に.huskyを作成できるため。
・Dockerfile と docker-compose.ymlは、未修正
→ issue #8 の内容を元に作成/変更する想定

2024-08-27 13:27 UTC, Asapi1020 commented on .gitignore
> +/backend/node_modules
```suggestion
node_modules
```
このように記述すればすべての階層のnode_modulesフォルダがignoreされます

2024-08-27 13:28 UTC, Asapi1020 commented on .gitignore
> +/frontend/.next/
ここもnode_modulesと同様ですが、nextは廃止予定なので単に削除でお願いします
（next廃止PRにまわしてもいいです）
```suggestion

```

2024-08-27 13:43 UTC, Asapi1020 requested changes
ルートディレクトリでも`pnpm init`で`package.json`を用意してください！
さらに`pnpm-workspace.yaml`を配置し、次のように記述します
```yaml
packages:
    - "frontend"
    - "backend"
```

こうすることで、共通のモジュール（eslintなど）はルートで一元管理され、リソースが最適化されます :D
（最適化そのものは手動で行う必要がある。つまり、eslintやprettierはルートでインストールし直し、frontendではアンストする）

2024-08-27 13:55 UTC, Asapi1020 commented on frontend/.husky/pre-commit
`.husky`は`.git`のある階層、つまりルートディレクトリにないと怒られます

husky自体はfrontとbackで分ける必要はないはずです
huskyが行うのは、コミット時にlintとtestをまわすこと
lint とtestの内容をfrontとbackでそれぞれ指定していれば、今回分離した意図は満たせるはずです

なお、`.husky/pre-commit`の中身には変更を加えなくて大丈夫です
ルートに配置した`package.json`を次のように書けば、frontとbackのscriptを並列して回せます
```json
{
    "test":  "pnpm -r --parallel test"
}
```
-rはいわゆるすべての階層を見るやつ。package.jsonがある階層でpnpm testが実行されます

2024-08-27 14:02 UTC, Asapi1020 commented
@WFrog2511 ディレクトリ構成変更お疲れ様です！コメントしたので対応おねがいします！

2024-08-31 09:18 UTC, WFrog2511 commented on .gitignore
> +/frontend/.next/
next廃止は別のPRにて行う形で進めます

2024-08-31 09:29 UTC, WFrog2511 commented
@Asapi1020 遅くなりましたが 修正しました。確認 よろしくお願いします。
※ frontend/package.jsonのnext.jsバージョンを誤って変えたままコミットしてしまいました、issue #13 に対応付けるブランチで next.jsを削除する予定です。

2024-08-31 12:27 UTC, Asapi1020 approved these changes

2024-08-31 12:28 UTC, Asapi1020 commented
LGTM!

2024-08-31 12:28 UTC, merged